-- Catálogos mínimos para una instalación nueva de MiHotel.
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;
INSERT INTO `tipo_clipro` (`id_tipoclipro`, `tipo`) VALUES (1,'cliente');
INSERT INTO `tipo_clipro` (`id_tipoclipro`, `tipo`) VALUES (2,'proveedor');
INSERT INTO `tipo_estado` (`id_tipoestado`, `estado`) VALUES (5,'activo');
INSERT INTO `tipo_estado` (`id_tipoestado`, `estado`) VALUES (6,'inactivo');
INSERT INTO `tipo_estado` (`id_tipoestado`, `estado`) VALUES (3,'libre');
INSERT INTO `tipo_estado` (`id_tipoestado`, `estado`) VALUES (4,'ocupada');
INSERT INTO `tipo_estado` (`id_tipoestado`, `estado`) VALUES (1,'remodelacion');
INSERT INTO `tipo_estado` (`id_tipoestado`, `estado`) VALUES (2,'renta');
INSERT INTO `tipo_movimiento` (`id_tipomov`, `nombre_tipomov`) VALUES (7,'abono');
INSERT INTO `tipo_movimiento` (`id_tipomov`, `nombre_tipomov`) VALUES (4,'anticipo_reserva');
INSERT INTO `tipo_movimiento` (`id_tipomov`, `nombre_tipomov`) VALUES (2,'compra');
INSERT INTO `tipo_movimiento` (`id_tipomov`, `nombre_tipomov`) VALUES (5,'cuenta_por_cobrar');
INSERT INTO `tipo_movimiento` (`id_tipomov`, `nombre_tipomov`) VALUES (6,'cuenta_por_pagar');
INSERT INTO `tipo_movimiento` (`id_tipomov`, `nombre_tipomov`) VALUES (8,'reembolso');
INSERT INTO `tipo_movimiento` (`id_tipomov`, `nombre_tipomov`) VALUES (3,'reserva');
INSERT INTO `tipo_movimiento` (`id_tipomov`, `nombre_tipomov`) VALUES (1,'venta');
INSERT INTO `tipo_proser` (`id_tipoproser`, `nombre`) VALUES (3,'habitacion');
INSERT INTO `tipo_proser` (`id_tipoproser`, `nombre`) VALUES (1,'producto');
INSERT INTO `tipo_proser` (`id_tipoproser`, `nombre`) VALUES (2,'servicio');
INSERT INTO `forma_pago` (`id_formapago`, `nombre_forma`) VALUES (5,'credito');
INSERT INTO `forma_pago` (`id_formapago`, `nombre_forma`) VALUES (2,'deposito');
INSERT INTO `forma_pago` (`id_formapago`, `nombre_forma`) VALUES (1,'efectivo');
INSERT INTO `forma_pago` (`id_formapago`, `nombre_forma`) VALUES (4,'tarjeta');
INSERT INTO `forma_pago` (`id_formapago`, `nombre_forma`) VALUES (3,'transferencia');
INSERT INTO `clasificacion_cliente` (`codigo`, `nombre`) VALUES ('B','Neutral');
INSERT INTO `clasificacion_cliente` (`codigo`, `nombre`) VALUES ('C','Problemático');
INSERT INTO `clasificacion_cliente` (`codigo`, `nombre`) VALUES ('A','Tranquilo');
INSERT INTO `unidad_medida` (`id_umedida`, `nombre`) VALUES (5,'kilo');
INSERT INTO `unidad_medida` (`id_umedida`, `nombre`) VALUES (4,'litro');
INSERT INTO `unidad_medida` (`id_umedida`, `nombre`) VALUES (3,'noche');
INSERT INTO `unidad_medida` (`id_umedida`, `nombre`) VALUES (2,'servicio');
INSERT INTO `unidad_medida` (`id_umedida`, `nombre`) VALUES (1,'unidad');
INSERT INTO `categoria` (`id_categoria`, `nombre_categoria`, `estado`, `es_sistema`) VALUES (1,'lacteos','activo',0);
INSERT INTO `categoria` (`id_categoria`, `nombre_categoria`, `estado`, `es_sistema`) VALUES (2,'bebidas','activo',0);
INSERT INTO `categoria` (`id_categoria`, `nombre_categoria`, `estado`, `es_sistema`) VALUES (3,'abarrotes','activo',0);
INSERT INTO `categoria` (`id_categoria`, `nombre_categoria`, `estado`, `es_sistema`) VALUES (4,'limpieza','activo',0);
INSERT INTO `categoria` (`id_categoria`, `nombre_categoria`, `estado`, `es_sistema`) VALUES (5,'Habitaciones','activo',1);
INSERT INTO `subcategoria` (`id_subcategoria`, `id_categoria`, `nombre_subcategoria`, `estado`, `precio`) VALUES (1,5,'Viajero','activo',250.00);
INSERT INTO `marca` (`id_marca`, `nombre_marca`, `estado`) VALUES (1,'generica','activo');
INSERT INTO `marca` (`id_marca`, `nombre_marca`, `estado`) VALUES (2,'Coca Cola','activo');
INSERT INTO `marca` (`id_marca`, `nombre_marca`, `estado`) VALUES (3,'Nescafe','activo');
INSERT INTO `marca` (`id_marca`, `nombre_marca`, `estado`) VALUES (4,'Pepsi','activo');
INSERT INTO `marca` (`id_marca`, `nombre_marca`, `estado`) VALUES (5,'Toledo','activo');
INSERT INTO `proser` (`id_proser`, `id_categoria`, `id_subcategoria`, `id_marca`, `id_umedida`, `id_tipoestado`, `id_tipoproser`, `codigo`, `nombre_proser`, `precio`, `stock`, `descripcion`) VALUES (1,5,1,NULL,3,3,3,'1','Habitación 1',0.00,0,NULL);
INSERT INTO `proser` (`id_proser`, `id_categoria`, `id_subcategoria`, `id_marca`, `id_umedida`, `id_tipoestado`, `id_tipoproser`, `codigo`, `nombre_proser`, `precio`, `stock`, `descripcion`) VALUES (2,5,1,NULL,3,3,3,'2','Habitación 2',0.00,0,NULL);
INSERT INTO `proser` (`id_proser`, `id_categoria`, `id_subcategoria`, `id_marca`, `id_umedida`, `id_tipoestado`, `id_tipoproser`, `codigo`, `nombre_proser`, `precio`, `stock`, `descripcion`) VALUES (3,5,1,NULL,3,3,3,'3','Habitación 3',0.00,0,NULL);
INSERT INTO `proser` (`id_proser`, `id_categoria`, `id_subcategoria`, `id_marca`, `id_umedida`, `id_tipoestado`, `id_tipoproser`, `codigo`, `nombre_proser`, `precio`, `stock`, `descripcion`) VALUES (4,5,1,NULL,3,3,3,'4','Habitación 4',0.00,0,NULL);
INSERT INTO `proser` (`id_proser`, `id_categoria`, `id_subcategoria`, `id_marca`, `id_umedida`, `id_tipoestado`, `id_tipoproser`, `codigo`, `nombre_proser`, `precio`, `stock`, `descripcion`) VALUES (5,5,1,NULL,3,3,3,'5','Habitación 5',0.00,0,NULL);
INSERT INTO `proser` (`id_proser`, `id_categoria`, `id_subcategoria`, `id_marca`, `id_umedida`, `id_tipoestado`, `id_tipoproser`, `codigo`, `nombre_proser`, `precio`, `stock`, `descripcion`) VALUES (6,5,1,NULL,3,3,3,'6','Habitación 6',0.00,0,NULL);
INSERT INTO `proser` (`id_proser`, `id_categoria`, `id_subcategoria`, `id_marca`, `id_umedida`, `id_tipoestado`, `id_tipoproser`, `codigo`, `nombre_proser`, `precio`, `stock`, `descripcion`) VALUES (7,5,1,NULL,3,3,3,'7','Habitación 7',0.00,0,NULL);
INSERT INTO `proser` (`id_proser`, `id_categoria`, `id_subcategoria`, `id_marca`, `id_umedida`, `id_tipoestado`, `id_tipoproser`, `codigo`, `nombre_proser`, `precio`, `stock`, `descripcion`) VALUES (8,5,1,NULL,3,3,3,'8','Habitación 8',0.00,0,NULL);
INSERT INTO `proser` (`id_proser`, `id_categoria`, `id_subcategoria`, `id_marca`, `id_umedida`, `id_tipoestado`, `id_tipoproser`, `codigo`, `nombre_proser`, `precio`, `stock`, `descripcion`) VALUES (9,5,1,NULL,3,3,3,'9','Habitación 9',0.00,0,NULL);
INSERT INTO `proser` (`id_proser`, `id_categoria`, `id_subcategoria`, `id_marca`, `id_umedida`, `id_tipoestado`, `id_tipoproser`, `codigo`, `nombre_proser`, `precio`, `stock`, `descripcion`) VALUES (10,5,1,NULL,3,3,3,'10','Habitación 10',0.00,0,NULL);
INSERT INTO `proser` (`id_proser`, `id_categoria`, `id_subcategoria`, `id_marca`, `id_umedida`, `id_tipoestado`, `id_tipoproser`, `codigo`, `nombre_proser`, `precio`, `stock`, `descripcion`) VALUES (11,5,1,NULL,3,3,3,'11','Habitación 11',0.00,0,NULL);
INSERT INTO `proser` (`id_proser`, `id_categoria`, `id_subcategoria`, `id_marca`, `id_umedida`, `id_tipoestado`, `id_tipoproser`, `codigo`, `nombre_proser`, `precio`, `stock`, `descripcion`) VALUES (12,5,1,NULL,3,3,3,'12','Habitación 12',0.00,0,NULL);
INSERT INTO `rol` (`id_rol`, `nombre_rol`, `estado`) VALUES (1,'admin','activo');
INSERT INTO `rol` (`id_rol`, `nombre_rol`, `estado`) VALUES (2,'recepcionista','activo');
INSERT INTO `rol` (`id_rol`, `nombre_rol`, `estado`) VALUES (3,'camarero','activo');
INSERT INTO `rol` (`id_rol`, `nombre_rol`, `estado`) VALUES (4,'cliente','activo');
INSERT INTO `permisos` (`id_permiso`, `nombre_permiso`, `descripcion`, `estado`) VALUES (1,'crear_usuario','Permite crear usuarios administrativos',1);
INSERT INTO `permisos` (`id_permiso`, `nombre_permiso`, `descripcion`, `estado`) VALUES (2,'editar_usuario','Permite editar usuarios administrativos',1);
INSERT INTO `permisos` (`id_permiso`, `nombre_permiso`, `descripcion`, `estado`) VALUES (3,'eliminar_usuario','Permite eliminar usuarios administrativos',1);
INSERT INTO `permisos` (`id_permiso`, `nombre_permiso`, `descripcion`, `estado`) VALUES (4,'ver_usuarios','Permite consultar usuarios administrativos',1);
INSERT INTO `permisos` (`id_permiso`, `nombre_permiso`, `descripcion`, `estado`) VALUES (5,'cambiar_estado_usuario','Permite activar o inactivar usuarios',1);
INSERT INTO `permisos` (`id_permiso`, `nombre_permiso`, `descripcion`, `estado`) VALUES (6,'resetear_clave_usuario','Permite restablecer la contraseña de usuarios',1);
INSERT INTO `permisos` (`id_permiso`, `nombre_permiso`, `descripcion`, `estado`) VALUES (7,'gestionar_roles','Permite administrar roles',1);
INSERT INTO `permisos` (`id_permiso`, `nombre_permiso`, `descripcion`, `estado`) VALUES (8,'gestionar_permisos','Permite administrar permisos y sus asignaciones',1);
INSERT INTO `permisos` (`id_permiso`, `nombre_permiso`, `descripcion`, `estado`) VALUES (9,'registrar_venta','Permite registrar ventas en el Punto de Venta',1);
INSERT INTO `permisos` (`id_permiso`, `nombre_permiso`, `descripcion`, `estado`) VALUES (10,'facturar','Permite gestionar solicitudes y adjuntar facturas emitidas',1);
INSERT INTO `permisos` (`id_permiso`, `nombre_permiso`, `descripcion`, `estado`) VALUES (11,'gestionar_inventario','Permite administrar y consultar inventario',1);
INSERT INTO `permisos` (`id_permiso`, `nombre_permiso`, `descripcion`, `estado`) VALUES (12,'gestionar_reservas','Permite administrar reservaciones',1);
INSERT INTO `permisos` (`id_permiso`, `nombre_permiso`, `descripcion`, `estado`) VALUES (13,'registrar_checkin','Permite registrar el ingreso de huéspedes',1);
INSERT INTO `permisos` (`id_permiso`, `nombre_permiso`, `descripcion`, `estado`) VALUES (14,'registrar_checkout','Permite registrar la salida de huéspedes',1);
INSERT INTO `permisos` (`id_permiso`, `nombre_permiso`, `descripcion`, `estado`) VALUES (15,'gestionar_cxc','Permite administrar cuentas por cobrar',1);
INSERT INTO `permisos` (`id_permiso`, `nombre_permiso`, `descripcion`, `estado`) VALUES (16,'gestionar_cxp','Permite administrar cuentas por pagar',1);
INSERT INTO `permisos` (`id_permiso`, `nombre_permiso`, `descripcion`, `estado`) VALUES (17,'realizar_reserva_online','Permite realizar reservaciones en línea',1);
INSERT INTO `permisos` (`id_permiso`, `nombre_permiso`, `descripcion`, `estado`) VALUES (18,'pagar_anticipo','Permite registrar pagos de reservaciones',1);
INSERT INTO `permisos` (`id_permiso`, `nombre_permiso`, `descripcion`, `estado`) VALUES (19,'ver_reservas','Permite consultar reservaciones',1);
INSERT INTO `permisos` (`id_permiso`, `nombre_permiso`, `descripcion`, `estado`) VALUES (20,'crear_reserva','Permite crear reservaciones',1);
INSERT INTO `permisos` (`id_permiso`, `nombre_permiso`, `descripcion`, `estado`) VALUES (21,'editar_reserva','Permite editar reservaciones',1);
INSERT INTO `permisos` (`id_permiso`, `nombre_permiso`, `descripcion`, `estado`) VALUES (22,'cancelar_reserva','Permite cancelar reservaciones',1);
INSERT INTO `permisos` (`id_permiso`, `nombre_permiso`, `descripcion`, `estado`) VALUES (23,'checkin','Permite ejecutar el check-in de una reservación',1);
INSERT INTO `permisos` (`id_permiso`, `nombre_permiso`, `descripcion`, `estado`) VALUES (24,'checkout','Permite ejecutar el check-out de una reservación',1);
INSERT INTO `permisos` (`id_permiso`, `nombre_permiso`, `descripcion`, `estado`) VALUES (25,'ver_clientes','Permite consultar clientes',1);
INSERT INTO `permisos` (`id_permiso`, `nombre_permiso`, `descripcion`, `estado`) VALUES (26,'registrar_cliente','Permite registrar clientes',1);
INSERT INTO `permisos` (`id_permiso`, `nombre_permiso`, `descripcion`, `estado`) VALUES (27,'ver_habitaciones','Permite consultar habitaciones',1);
INSERT INTO `permisos` (`id_permiso`, `nombre_permiso`, `descripcion`, `estado`) VALUES (28,'ver_disponibilidad_habitaciones','Permite consultar disponibilidad de habitaciones',1);
INSERT INTO `permisos` (`id_permiso`, `nombre_permiso`, `descripcion`, `estado`) VALUES (29,'ver_menu','Permite consultar productos y servicios disponibles',1);
INSERT INTO `permisos` (`id_permiso`, `nombre_permiso`, `descripcion`, `estado`) VALUES (30,'registrar_consumo','Permite registrar consumos',1);
INSERT INTO `permisos` (`id_permiso`, `nombre_permiso`, `descripcion`, `estado`) VALUES (31,'cobrar_cuenta','Permite cobrar cuentas',1);
INSERT INTO `permisos` (`id_permiso`, `nombre_permiso`, `descripcion`, `estado`) VALUES (32,'ver_disponibilidad_productos','Permite consultar disponibilidad de productos',1);
INSERT INTO `permisos` (`id_permiso`, `nombre_permiso`, `descripcion`, `estado`) VALUES (33,'ver_reservas_propias','Permite al cliente consultar sus reservaciones',1);
INSERT INTO `permisos` (`id_permiso`, `nombre_permiso`, `descripcion`, `estado`) VALUES (34,'ver_pagos_propios','Permite al cliente consultar sus pagos',1);
INSERT INTO `permisos` (`id_permiso`, `nombre_permiso`, `descripcion`, `estado`) VALUES (35,'ver_saldos_pendientes','Permite al cliente consultar sus saldos pendientes',1);
INSERT INTO `permisos` (`id_permiso`, `nombre_permiso`, `descripcion`, `estado`) VALUES (36,'actualizar_datos_propios','Permite al cliente actualizar sus datos personales',1);
INSERT INTO `permisos` (`id_permiso`, `nombre_permiso`, `descripcion`, `estado`) VALUES (37,'editar_clientes','Permite editar clientes, documentos y estados',1);
INSERT INTO `permisos` (`id_permiso`, `nombre_permiso`, `descripcion`, `estado`) VALUES (38,'gestionar_habitaciones','Permite crear, editar y administrar habitaciones',1);
INSERT INTO `permisos` (`id_permiso`, `nombre_permiso`, `descripcion`, `estado`) VALUES (39,'gestionar_empresas_clientes','Permite administrar empresas de procedencia',1);
INSERT INTO `permisos` (`id_permiso`, `nombre_permiso`, `descripcion`, `estado`) VALUES (40,'ver_trabajadores','Permite consultar trabajadores y contactos',1);
INSERT INTO `permisos` (`id_permiso`, `nombre_permiso`, `descripcion`, `estado`) VALUES (41,'gestionar_trabajadores','Permite crear, editar y cambiar el estado de trabajadores',1);
INSERT INTO `permisos` (`id_permiso`, `nombre_permiso`, `descripcion`, `estado`) VALUES (42,'gestionar_mantenimientos','Permite registrar, editar y completar mantenimientos',1);
INSERT INTO `permisos` (`id_permiso`, `nombre_permiso`, `descripcion`, `estado`) VALUES (43,'ver_historial_ventas','Permite consultar el historial y detalle de ventas',1);
INSERT INTO `permisos` (`id_permiso`, `nombre_permiso`, `descripcion`, `estado`) VALUES (44,'ver_facturas','Permite consultar solicitudes y documentos de facturación',1);
INSERT INTO `permisos` (`id_permiso`, `nombre_permiso`, `descripcion`, `estado`) VALUES (45,'anular_factura','Permite anular documentos fiscales adjuntos',1);
INSERT INTO `permisos` (`id_permiso`, `nombre_permiso`, `descripcion`, `estado`) VALUES (46,'ver_reportes','Permite consultar reportes operativos',1);
INSERT INTO `permisos` (`id_permiso`, `nombre_permiso`, `descripcion`, `estado`) VALUES (47,'gestionar_compras','Permite registrar y consultar compras',1);
INSERT INTO `permisos` (`id_permiso`, `nombre_permiso`, `descripcion`, `estado`) VALUES (48,'gestionar_proveedores','Permite administrar proveedores',1);
INSERT INTO `permisos` (`id_permiso`, `nombre_permiso`, `descripcion`, `estado`) VALUES (49,'gestionar_productos_servicios','Permite administrar productos y servicios',1);
INSERT INTO `permisos` (`id_permiso`, `nombre_permiso`, `descripcion`, `estado`) VALUES (50,'gestionar_catalogos','Permite administrar categorías, subcategorías y marcas',1);
INSERT INTO `permisos` (`id_permiso`, `nombre_permiso`, `descripcion`, `estado`) VALUES (51,'gestionar_configuracion','Permite modificar recargos e impuestos del sistema',1);
INSERT INTO `permisos` (`id_permiso`, `nombre_permiso`, `descripcion`, `estado`) VALUES (52,'usar_simulacion_precios','Permite utilizar la simulación de precios',1);
INSERT INTO `rol_permiso` (`id_rol`, `id_permiso`) VALUES (1,1);
INSERT INTO `rol_permiso` (`id_rol`, `id_permiso`) VALUES (1,2);
INSERT INTO `rol_permiso` (`id_rol`, `id_permiso`) VALUES (1,3);
INSERT INTO `rol_permiso` (`id_rol`, `id_permiso`) VALUES (1,4);
INSERT INTO `rol_permiso` (`id_rol`, `id_permiso`) VALUES (1,5);
INSERT INTO `rol_permiso` (`id_rol`, `id_permiso`) VALUES (1,6);
INSERT INTO `rol_permiso` (`id_rol`, `id_permiso`) VALUES (1,7);
INSERT INTO `rol_permiso` (`id_rol`, `id_permiso`) VALUES (1,8);
INSERT INTO `rol_permiso` (`id_rol`, `id_permiso`) VALUES (1,9);
INSERT INTO `rol_permiso` (`id_rol`, `id_permiso`) VALUES (2,9);
INSERT INTO `rol_permiso` (`id_rol`, `id_permiso`) VALUES (3,9);
INSERT INTO `rol_permiso` (`id_rol`, `id_permiso`) VALUES (1,10);
INSERT INTO `rol_permiso` (`id_rol`, `id_permiso`) VALUES (2,10);
INSERT INTO `rol_permiso` (`id_rol`, `id_permiso`) VALUES (1,11);
INSERT INTO `rol_permiso` (`id_rol`, `id_permiso`) VALUES (1,12);
INSERT INTO `rol_permiso` (`id_rol`, `id_permiso`) VALUES (2,12);
INSERT INTO `rol_permiso` (`id_rol`, `id_permiso`) VALUES (1,13);
INSERT INTO `rol_permiso` (`id_rol`, `id_permiso`) VALUES (2,13);
INSERT INTO `rol_permiso` (`id_rol`, `id_permiso`) VALUES (1,14);
INSERT INTO `rol_permiso` (`id_rol`, `id_permiso`) VALUES (2,14);
INSERT INTO `rol_permiso` (`id_rol`, `id_permiso`) VALUES (1,15);
INSERT INTO `rol_permiso` (`id_rol`, `id_permiso`) VALUES (2,15);
INSERT INTO `rol_permiso` (`id_rol`, `id_permiso`) VALUES (1,16);
INSERT INTO `rol_permiso` (`id_rol`, `id_permiso`) VALUES (1,17);
INSERT INTO `rol_permiso` (`id_rol`, `id_permiso`) VALUES (4,17);
INSERT INTO `rol_permiso` (`id_rol`, `id_permiso`) VALUES (1,18);
INSERT INTO `rol_permiso` (`id_rol`, `id_permiso`) VALUES (1,19);
INSERT INTO `rol_permiso` (`id_rol`, `id_permiso`) VALUES (2,19);
INSERT INTO `rol_permiso` (`id_rol`, `id_permiso`) VALUES (1,20);
INSERT INTO `rol_permiso` (`id_rol`, `id_permiso`) VALUES (2,20);
INSERT INTO `rol_permiso` (`id_rol`, `id_permiso`) VALUES (4,20);
INSERT INTO `rol_permiso` (`id_rol`, `id_permiso`) VALUES (1,21);
INSERT INTO `rol_permiso` (`id_rol`, `id_permiso`) VALUES (2,21);
INSERT INTO `rol_permiso` (`id_rol`, `id_permiso`) VALUES (1,22);
INSERT INTO `rol_permiso` (`id_rol`, `id_permiso`) VALUES (2,22);
INSERT INTO `rol_permiso` (`id_rol`, `id_permiso`) VALUES (1,23);
INSERT INTO `rol_permiso` (`id_rol`, `id_permiso`) VALUES (2,23);
INSERT INTO `rol_permiso` (`id_rol`, `id_permiso`) VALUES (1,24);
INSERT INTO `rol_permiso` (`id_rol`, `id_permiso`) VALUES (2,24);
INSERT INTO `rol_permiso` (`id_rol`, `id_permiso`) VALUES (1,25);
INSERT INTO `rol_permiso` (`id_rol`, `id_permiso`) VALUES (2,25);
INSERT INTO `rol_permiso` (`id_rol`, `id_permiso`) VALUES (1,26);
INSERT INTO `rol_permiso` (`id_rol`, `id_permiso`) VALUES (2,26);
INSERT INTO `rol_permiso` (`id_rol`, `id_permiso`) VALUES (1,27);
INSERT INTO `rol_permiso` (`id_rol`, `id_permiso`) VALUES (2,27);
INSERT INTO `rol_permiso` (`id_rol`, `id_permiso`) VALUES (1,28);
INSERT INTO `rol_permiso` (`id_rol`, `id_permiso`) VALUES (2,28);
INSERT INTO `rol_permiso` (`id_rol`, `id_permiso`) VALUES (1,29);
INSERT INTO `rol_permiso` (`id_rol`, `id_permiso`) VALUES (3,29);
INSERT INTO `rol_permiso` (`id_rol`, `id_permiso`) VALUES (1,30);
INSERT INTO `rol_permiso` (`id_rol`, `id_permiso`) VALUES (3,30);
INSERT INTO `rol_permiso` (`id_rol`, `id_permiso`) VALUES (1,31);
INSERT INTO `rol_permiso` (`id_rol`, `id_permiso`) VALUES (2,31);
INSERT INTO `rol_permiso` (`id_rol`, `id_permiso`) VALUES (1,32);
INSERT INTO `rol_permiso` (`id_rol`, `id_permiso`) VALUES (3,32);
INSERT INTO `rol_permiso` (`id_rol`, `id_permiso`) VALUES (1,33);
INSERT INTO `rol_permiso` (`id_rol`, `id_permiso`) VALUES (4,33);
INSERT INTO `rol_permiso` (`id_rol`, `id_permiso`) VALUES (1,34);
INSERT INTO `rol_permiso` (`id_rol`, `id_permiso`) VALUES (4,34);
INSERT INTO `rol_permiso` (`id_rol`, `id_permiso`) VALUES (1,35);
INSERT INTO `rol_permiso` (`id_rol`, `id_permiso`) VALUES (4,35);
INSERT INTO `rol_permiso` (`id_rol`, `id_permiso`) VALUES (1,36);
INSERT INTO `rol_permiso` (`id_rol`, `id_permiso`) VALUES (4,36);
INSERT INTO `rol_permiso` (`id_rol`, `id_permiso`) VALUES (1,37);
INSERT INTO `rol_permiso` (`id_rol`, `id_permiso`) VALUES (2,37);
INSERT INTO `rol_permiso` (`id_rol`, `id_permiso`) VALUES (1,38);
INSERT INTO `rol_permiso` (`id_rol`, `id_permiso`) VALUES (1,39);
INSERT INTO `rol_permiso` (`id_rol`, `id_permiso`) VALUES (2,39);
INSERT INTO `rol_permiso` (`id_rol`, `id_permiso`) VALUES (1,40);
INSERT INTO `rol_permiso` (`id_rol`, `id_permiso`) VALUES (2,40);
INSERT INTO `rol_permiso` (`id_rol`, `id_permiso`) VALUES (1,41);
INSERT INTO `rol_permiso` (`id_rol`, `id_permiso`) VALUES (1,42);
INSERT INTO `rol_permiso` (`id_rol`, `id_permiso`) VALUES (2,42);
INSERT INTO `rol_permiso` (`id_rol`, `id_permiso`) VALUES (1,43);
INSERT INTO `rol_permiso` (`id_rol`, `id_permiso`) VALUES (2,43);
INSERT INTO `rol_permiso` (`id_rol`, `id_permiso`) VALUES (1,44);
INSERT INTO `rol_permiso` (`id_rol`, `id_permiso`) VALUES (2,44);
INSERT INTO `rol_permiso` (`id_rol`, `id_permiso`) VALUES (1,45);
INSERT INTO `rol_permiso` (`id_rol`, `id_permiso`) VALUES (1,46);
INSERT INTO `rol_permiso` (`id_rol`, `id_permiso`) VALUES (2,46);
INSERT INTO `rol_permiso` (`id_rol`, `id_permiso`) VALUES (1,47);
INSERT INTO `rol_permiso` (`id_rol`, `id_permiso`) VALUES (1,48);
INSERT INTO `rol_permiso` (`id_rol`, `id_permiso`) VALUES (1,49);
INSERT INTO `rol_permiso` (`id_rol`, `id_permiso`) VALUES (1,50);
INSERT INTO `rol_permiso` (`id_rol`, `id_permiso`) VALUES (1,51);
INSERT INTO `rol_permiso` (`id_rol`, `id_permiso`) VALUES (1,52);
INSERT INTO configuracion_sistema
    (id_configuracion, recargo_tarjeta, iva_porcentaje, impuesto_turismo_porcentaje, fecha_actualizacion, id_usuario_actualizacion)
VALUES
    (1, 25.00, 12.00, 10.00, CURRENT_TIMESTAMP, NULL)
ON DUPLICATE KEY UPDATE id_configuracion = id_configuracion;

SET FOREIGN_KEY_CHECKS=1;
