<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="MySql.Data">
      <HintPath>..\..\MiHotel\bin\Debug\net8.0\MySql.Data.dll</HintPath>
    </Reference>
    <None Include="..\..\MiHotel\bin\Debug\net8.0\*.dll" CopyToOutputDirectory="PreserveNewest" Visible="false" />
  </ItemGroup>
</Project>
